# Set the platform to iOS 15.0
platform :ios, '15.0'

# CocoaPods analytics
plugin 'cocoapods-disable-podfile-validations'

# Flutter setup
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This pulls in all your flutter pubspec packages automatically
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Force every native plugin dependency to compile for iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end