# 1. This block tells CocoaPods where to find Flutter's custom Ruby methods
python_path = File.expand_file_path('..', __dir__)
flutter_root = File.expand_path(File.join('..', '..'), __dir__)

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'), ENV['FLUTTER_ROOT'] || flutter_root)

platform :ios, '15.0'

plugin 'cocoapods-disable-podfile-validations'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 2. This will now run successfully because of the 'require' statement above
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end